// This file is auto-generated by scripts/render_previews.mjs.
// Do not edit manually — your changes will be overwritten.
//
// The render script extracts the actual class name from the
// contributor's component file and injects it here.

import 'package:flutter/material.dart';
import 'component.dart';

void main() => runApp(const PreviewApp());

class PreviewApp extends StatelessWidget {
  const PreviewApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorSchemeSeed: const Color(0xFF4F46E5),
        useMaterial3: true,
      ),
      home: const Scaffold(
        backgroundColor: Color(0xFFF8F8F7),
        body: Center(
          child: PreviewComponent(),
        ),
      ),
    );
  }
}
