name: Deploy Previews

on:
  push:
    branches:
      - main
    paths:
      - 'registry/**/*.dart'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: registry/**/*.dart

      - name: Render and Upload Previews
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        run: |
          changedFiles="${{ steps.changed-files.outputs.all_changed_files }}"
          
          # Read changed files dynamically using bash
          for file in $changedFiles; do
            if [[ $file == registry/*/*/* ]]; then
              IFS='/' read -ra PARTS <<< "$file"
              Component="${PARTS[1]}"
              Variant="${PARTS[2]}"
              
              echo "Triggering build for Component: $Component, Variant: $Variant"
              node ./scripts/render_previews.mjs --Component "$Component" --Variant "$Variant" --PushToR2 true
            fi
          done
